import { bigint, boolean, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: uuid('id').primaryKey().defaultRandom(),
  email: text('email').notNull().unique(),
  passwordHash: text('password_hash').notNull(),
  emailVerifiedAt: timestamp('email_verified_at', { withTimezone: true }),
  twoFactorEnabled: boolean('two_factor_enabled').notNull().default(false),
  /** AES-256-GCM encrypted TOTP secret, set once two-factor is enabled. */
  twoFactorSecret: text('two_factor_secret'),
  /** Encrypted TOTP secret generated by setup, promoted on enable. */
  twoFactorPendingSecret: text('two_factor_pending_secret'),
  /** Last accepted TOTP time step, to reject replayed codes. */
  twoFactorLastUsedStep: bigint('two_factor_last_used_step', {
    mode: 'number',
  }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export type UserRow = typeof users.$inferSelect;
export type NewUserRow = typeof users.$inferInsert;
